### ISSUE TITLE
Dump not working

### ISSUE THREAD

**Issue by corsch** [Kudaes/Dumpy#1] opened 2022-06-20 14:11 UTC
Sometimes dumpy is not working.
The "starting analysis..." part takes a lot longer than normal.

```
C:\Temp>dumpy dump
[+] SeDebugPrivilege successfully enabled.
[+] Retrieved 42708 handles. Starting analysis...
```

Normal it looks like this:
```
C:\Temp>dumpy dump
[+] SeDebugPrivilege successfully enabled.
[+] Retrieved 54767 handles. Starting analysis...
[+] NtOpenProcess hooked.
[!] Lsass dump created!
[+] Memory dump written to file epvk4mF.txt.
[+] Successfully unmapped view of file.
[+] Transaction successfully rollbacked.
```

Unfortunately I cannot see a debug switch to get a verbose output.

**Comment by Kudaes** [comment] 2022-06-20 15:08
Hi @corsch,

Give me a little bit more of context: are those two executions being performed on the same machine? is it x64 or x86?
There is not a debug switch yet, but you can enable the debug output at compilation time. In order to do that, please go to the cargo.toml file inside the folder dumper and change the value of the variable "debug" from 0 to 2 (which means full debug output). Then compile and execute again, and let me know if it throws any exception message.

I've been able to reproduce this scenario on very few ocassions, and everytimes it just meant that it didn't find in the system a valid handle to lsass. I think that I really need to add a message for that ocassions... :P

**Comment by Kudaes** [comment] 2022-06-20 17:10
Hi again @corsch ,

I think I've found the issue. There was a massive memory leak since I wasn't closing all the opened handles. I've pushed and
 update and now it seems like it's working properly everytime (but please confirm it if you can).

Besides that, I'll add a "--max-handles" switch in order to stop the execution after a certain amount of handles analyzed since I rarely get a dump after the first 30k handles. In that cases it's better to restart the execution after a while cause you never know when a new handle will be opened.

**Comment by corsch** [comment] 2022-06-20 18:28
Hey @Kudaes,

thank you very much for your reply!
Both systems are x64 and I'll guess that there was just no handle open on lsass.exe.
An output would be great :)

I'll test your new version tomorrow :)

**Comment by corsch** [comment] 2022-06-21 07:16
Very nice work! :)

```
[+] SeDebugPrivilege successfully enabled.
[+] Retrieved 60121 handles. Starting analysis...
  \ 10000 handles have been analyzed so far...
  \ 20000 handles have been analyzed so far...
  \ 30000 handles have been analyzed so far...
  \ 40000 handles have been analyzed so far...
  \ 50000 handles have been analyzed so far...
  \ 60000 handles have been analyzed so far...
[x] Could not retrieve a valid handle. Exiting.
```

**Closed as completed** 2022-06-21 07:18 UTC
